#!/bin/bash
set -euo pipefail

MICROSCANNER_TOKEN="${MICROSCANNER_TOKEN:-}"
MICROSCANNER_OPTIONS="${MICROSCANNER_OPTIONS:-}"
DOCKER_IMAGE="${1:-}"

MICROSCANNER_TOKEN=${MICROSCANNER_TOKEN} MICROSCANNER_OPTIONS=$MICROSCANNER_OPTIONS  ./scan.sh "${DOCKER_IMAGE}" | sed -n '/scan_started/,/Removing intermediate/p' | head -n -1 | sed '1 i {'
