#!/bin/bash
set -euo pipefail

MICROSCANNER_TOKEN="${MICROSCANNER_TOKEN:-}"
MICROSCANNER_OPTIONS="${MICROSCANNER_OPTIONS:-}"
DOCKER_IMAGE="${1:-}"

MICROSCANNER_TOKEN=${MICROSCANNER_TOKEN} MICROSCANNER_OPTIONS=$MICROSCANNER_OPTIONS  ./scan.sh ${DOCKER_IMAGE} | awk 'flag; /{/{flag=1} /}/{flag=0}'
echo }
